# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/ui_generated/qt5/modify_person_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(400, 300)
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.statusLabel = QtWidgets.QLabel(self.frame)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.statusLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.allowed_radio_button = QtWidgets.QRadioButton(self.frame)
        self.allowed_radio_button.setChecked(False)
        self.allowed_radio_button.setObjectName("allowed_radio_button")
        self.horizontalLayout.addWidget(self.allowed_radio_button)
        self.denied_radio_button = QtWidgets.QRadioButton(self.frame)
        self.denied_radio_button.setObjectName("denied_radio_button")
        self.horizontalLayout.addWidget(self.denied_radio_button)
        self.pending_radio_button = QtWidgets.QRadioButton(self.frame)
        self.pending_radio_button.setChecked(True)
        self.pending_radio_button.setObjectName("pending_radio_button")
        self.horizontalLayout.addWidget(self.pending_radio_button)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Person"))
        self.nameLabel.setText(_translate("Dialog", "Name:"))
        self.statusLabel.setText(_translate("Dialog", "Status:"))
        self.allowed_radio_button.setText(_translate("Dialog", "Allowed"))
        self.denied_radio_button.setText(_translate("Dialog", "Denied"))
        self.pending_radio_button.setText(_translate("Dialog", "Pending"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
